import { SeniorProfile } from './types';

export const SENIORS_DATA: SeniorProfile[] = [
  // --- FINANCE ---
  {
    id: '1',
    name: 'Aravind Iyer',
    field: 'Finance',
    company: 'Goldman Sachs',
    role: 'Investment Banking Associate',
    undergradDegree: 'B.Com (Hons)',
    preMbaExperienceYears: 2,
    preMbaIndustry: 'Audit (Big 4)',
    clubsAndCommittees: ['Finance Club', 'Placement Committee'],
    bio: 'Pivoted from Audit to IB. Happy to guide CAs and commerce grads.',
  },
  {
    id: '2',
    name: 'Sneha Gupta',
    field: 'Finance',
    company: 'JP Morgan Chase',
    role: 'Markets Analyst',
    undergradDegree: 'B.Tech Computer Science',
    preMbaExperienceYears: 0,
    preMbaIndustry: 'N/A',
    clubsAndCommittees: ['Investments Society'],
    bio: 'Engineer turned Finance enthusiast. Expert in CFA prep and quant roles.',
  },
  {
    id: '3',
    name: 'Rohan Mehta',
    field: 'Finance',
    company: 'Avendus Capital',
    role: 'PE Associate',
    undergradDegree: 'BBA',
    preMbaExperienceYears: 3,
    preMbaIndustry: 'Boutique IB',
    clubsAndCommittees: ['Alumni Committee'],
    bio: 'Deep experience in Private Equity and deal structuring.',
  },
  {
    id: '4',
    name: 'Ishita Sharma',
    field: 'Finance',
    company: 'HDFC Bank',
    role: 'Management Trainee',
    undergradDegree: 'Economics (Hons)',
    preMbaExperienceYears: 1,
    preMbaIndustry: 'Research',
    clubsAndCommittees: ['Finance Club'],
    bio: 'Corporate banking roles and general management in BFSI.',
  },
  {
    id: '5',
    name: 'Karan Malhotra',
    field: 'Finance',
    company: 'Standard Chartered',
    role: 'Wealth Manager',
    undergradDegree: 'B.Com',
    preMbaExperienceYears: 4,
    preMbaIndustry: 'Family Business',
    clubsAndCommittees: ['Entrepreneurship Cell'],
    bio: 'Focus on wealth management and HNI client relations.',
  },
  {
    id: '6',
    name: 'Vikram Singh',
    field: 'Finance',
    company: 'Credit Suisse',
    role: 'Risk Analyst',
    undergradDegree: 'B.Tech Mechanical',
    preMbaExperienceYears: 2,
    preMbaIndustry: 'Manufacturing',
    clubsAndCommittees: ['Quant Club'],
    bio: 'Transitioned from core engineering to Financial Risk Management.',
  },

  // --- CONSULTING ---
  {
    id: '7',
    name: 'Priya Desai',
    field: 'Consulting',
    company: 'McKinsey & Co',
    role: 'Associate',
    undergradDegree: 'B.Tech Electrical (IIT)',
    preMbaExperienceYears: 2,
    preMbaIndustry: 'Software Dev',
    clubsAndCommittees: ['Consulting Club', 'Student Council'],
    bio: 'Classic engineer-to-consultant path. Case prep expert.',
  },
  {
    id: '8',
    name: 'Rahul Verma',
    field: 'Consulting',
    company: 'BCG',
    role: 'Senior Associate',
    undergradDegree: 'CA',
    preMbaExperienceYears: 3,
    preMbaIndustry: 'Taxation',
    clubsAndCommittees: ['Debating Society'],
    bio: 'Helping CAs break into MBB. Focus on strategy and public sector projects.',
  },
  {
    id: '9',
    name: 'Ananya Roy',
    field: 'Consulting',
    company: 'Accenture Strategy',
    role: 'Consultant',
    undergradDegree: 'B.A. Psychology',
    preMbaExperienceYears: 1,
    preMbaIndustry: 'NGO/Social Impact',
    clubsAndCommittees: ['Social Impact Club'],
    bio: 'Non-engineering background. Focus on change management and HR transformation.',
  },
  {
    id: '10',
    name: 'Siddharth Jain',
    field: 'Consulting',
    company: 'Deloitte USI',
    role: 'Senior Consultant',
    undergradDegree: 'B.Tech IT',
    preMbaExperienceYears: 4,
    preMbaIndustry: 'IT Services',
    clubsAndCommittees: ['Tech Club'],
    bio: 'Tech consulting and digital transformation projects.',
  },
  {
    id: '11',
    name: 'Meera Reddy',
    field: 'Consulting',
    company: 'KPMG',
    role: 'Management Consultant',
    undergradDegree: 'BBA',
    preMbaExperienceYears: 0,
    preMbaIndustry: 'N/A',
    clubsAndCommittees: ['Case Study Club'],
    bio: 'Fresher who cracked the consulting code through rigorous case prep.',
  },
  {
    id: '12',
    name: 'Arjun Nair',
    field: 'Consulting',
    company: 'Bain & Co',
    role: 'Associate Consultant',
    undergradDegree: 'B.Sc Statistics',
    preMbaExperienceYears: 2,
    preMbaIndustry: 'Data Analytics',
    clubsAndCommittees: ['Consulting Club'],
    bio: 'Data-driven consulting. Heavy focus on analytics projects.',
  },

  // --- MARKETING ---
  {
    id: '13',
    name: 'Kabir Bedi',
    field: 'Marketing',
    company: 'HUL',
    role: 'Management Trainee',
    undergradDegree: 'B.Tech Chemical',
    preMbaExperienceYears: 2,
    preMbaIndustry: 'Oil & Gas',
    clubsAndCommittees: ['Marketing Club'],
    bio: 'FMCG sales and marketing enthusiast. Rural stint experience.',
  },
  {
    id: '14',
    name: 'Simran Kaur',
    field: 'Marketing',
    company: 'Procter & Gamble',
    role: 'Brand Manager',
    undergradDegree: 'B.A. Economics',
    preMbaExperienceYears: 1,
    preMbaIndustry: 'Advertising Agency',
    clubsAndCommittees: ['Media Committee'],
    bio: 'Creative side of marketing. Brand building and digital campaigns.',
  },
  {
    id: '15',
    name: 'Aditya Chopra',
    field: 'Marketing',
    company: 'Google',
    role: 'Product Marketing Manager',
    undergradDegree: 'B.Tech CS',
    preMbaExperienceYears: 3,
    preMbaIndustry: 'Tech Startup',
    clubsAndCommittees: ['Tech Club', 'Marketing Club'],
    bio: 'Intersection of Tech and Marketing. GTM strategies for SaaS products.',
  },
  {
    id: '16',
    name: 'Neha Kapoor',
    field: 'Marketing',
    company: 'L\'Oreal',
    role: 'Marketing Manager',
    undergradDegree: 'Fashion Technology',
    preMbaExperienceYears: 2,
    preMbaIndustry: 'Retail',
    clubsAndCommittees: ['Cultural Committee'],
    bio: 'Luxury brand management and fashion retail.',
  },
  {
    id: '17',
    name: 'Varun Dhawan',
    field: 'Marketing',
    company: 'Amazon',
    role: 'Program Manager',
    undergradDegree: 'BBA',
    preMbaExperienceYears: 0,
    preMbaIndustry: 'N/A',
    clubsAndCommittees: ['E-Cell'],
    bio: 'E-commerce marketing and vendor management.',
  },
  {
    id: '18',
    name: 'Riya Sen',
    field: 'Marketing',
    company: 'PepsiCo',
    role: 'Sales Manager',
    undergradDegree: 'B.Com',
    preMbaExperienceYears: 1,
    preMbaIndustry: 'Sales',
    clubsAndCommittees: ['Sports Committee'],
    bio: 'Hardcore sales profiles and distribution networks.',
  },

  // --- OPERATIONS / GEN MAN ---
  {
    id: '19',
    name: 'Rajesh Koothrappali',
    field: 'Operations',
    company: 'Uber',
    role: 'Operations Manager',
    undergradDegree: 'B.Tech Civil',
    preMbaExperienceYears: 3,
    preMbaIndustry: 'Construction',
    clubsAndCommittees: ['Ops Club'],
    bio: 'City operations and logistics optimization.',
  },
  {
    id: '20',
    name: 'Penny Hofstadter',
    field: 'Operations',
    company: 'Tata Steel',
    role: 'Supply Chain Manager',
    undergradDegree: 'B.Tech Mechanical',
    preMbaExperienceYears: 4,
    preMbaIndustry: 'Automotive',
    clubsAndCommittees: ['Industrial Interaction Club'],
    bio: 'Manufacturing operations and heavy industry supply chain.',
  },
  {
    id: '21',
    name: 'Sheldon Cooper',
    field: 'Operations',
    company: 'Flipkart',
    role: 'Supply Chain Analyst',
    undergradDegree: 'B.Sc Physics',
    preMbaExperienceYears: 0,
    preMbaIndustry: 'N/A',
    clubsAndCommittees: ['Science Club'],
    bio: 'Warehousing, last-mile delivery, and inventory planning.',
  },
  {
    id: '22',
    name: 'Leonard Hofstadter',
    field: 'General Management',
    company: 'TAS (Tata Administrative Services)',
    role: 'Manager',
    undergradDegree: 'B.Tech Electrical',
    preMbaExperienceYears: 2,
    preMbaIndustry: 'Power Sector',
    clubsAndCommittees: ['Student Council'],
    bio: 'Leadership roles across diverse Tata group companies.',
  },
  {
    id: '23',
    name: 'Howard Wolowitz',
    field: 'Operations',
    company: 'Boeing',
    role: 'Project Manager',
    undergradDegree: 'B.Tech Aerospace',
    preMbaExperienceYears: 5,
    preMbaIndustry: 'Aviation',
    clubsAndCommittees: ['Tech Club'],
    bio: 'Project management in high-tech engineering sectors.',
  },
  {
    id: '24',
    name: 'Bernadette Rostenkowski',
    field: 'General Management',
    company: 'Mahindra GMC',
    role: 'Group Management Cadre',
    undergradDegree: 'B.Sc Biotech',
    preMbaExperienceYears: 1,
    preMbaIndustry: 'Pharma',
    clubsAndCommittees: ['Alumni Committee'],
    bio: 'General management with a focus on healthcare and agri-tech.',
  },

  // --- HR ---
  {
    id: '25',
    name: 'Monica Geller',
    field: 'HR',
    company: 'Microsoft',
    role: 'HR Business Partner',
    undergradDegree: 'B.A. Psychology',
    preMbaExperienceYears: 2,
    preMbaIndustry: 'Recruitment Agency',
    clubsAndCommittees: ['HR Club'],
    bio: 'Tech HR, talent management, and organizational culture.',
  },
  {
    id: '26',
    name: 'Rachel Green',
    field: 'HR',
    company: 'Aditya Birla Group',
    role: 'HR Manager',
    undergradDegree: 'B.A. English',
    preMbaExperienceYears: 0,
    preMbaIndustry: 'N/A',
    clubsAndCommittees: ['Cultural Committee'],
    bio: 'Leadership development programs and employee engagement.',
  },
  {
    id: '27',
    name: 'Chandler Bing',
    field: 'HR',
    company: 'InfoEdge (Naukri)',
    role: 'Talent Acquisition Manager',
    undergradDegree: 'B.Com',
    preMbaExperienceYears: 3,
    preMbaIndustry: 'Data Processing',
    clubsAndCommittees: ['HR Club', 'Placement Committee'],
    bio: 'Recruitment strategy and employer branding.',
  },
  {
    id: '28',
    name: 'Joey Tribbiani',
    field: 'HR',
    company: 'Reliance Industries',
    role: 'Labor Relations Manager',
    undergradDegree: 'B.A. Sociology',
    preMbaExperienceYears: 1,
    preMbaIndustry: 'Hospitality',
    clubsAndCommittees: ['Dramatics Club'],
    bio: 'Industrial relations and factory HR management.',
  },
  {
    id: '29',
    name: 'Phoebe Buffay',
    field: 'HR',
    company: 'ITC',
    role: 'HR Specialist',
    undergradDegree: 'B.Sc Environmental Science',
    preMbaExperienceYears: 2,
    preMbaIndustry: 'Non-Profit',
    clubsAndCommittees: ['Social Impact Club'],
    bio: 'Diversity and Inclusion initiatives.',
  },
  {
    id: '30',
    name: 'Gunther Central',
    field: 'HR',
    company: 'Wipro',
    role: 'Compensation & Benefits Analyst',
    undergradDegree: 'B.Com',
    preMbaExperienceYears: 4,
    preMbaIndustry: 'Payroll Processing',
    clubsAndCommittees: ['Fin-HR Interest Group'],
    bio: 'Rewards, payroll, and compensation structuring.',
  },
];